# Generated by Django 4.1.3 on 2023-04-17 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DecodeApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='upassword',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
