# Generated by Django 4.1.3 on 2023-04-19 11:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DecodeApp', '0002_user_upassword'),
    ]

    operations = [
        migrations.CreateModel(
            name='blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('postedDate', models.DateField(default=datetime.date(2023, 4, 19))),
                ('good_name', models.CharField(max_length=200)),
            ],
        ),
    ]
