# Generated by Django 4.1.3 on 2023-04-20 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DecodeApp', '0004_alter_blog_posteddate'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuerySend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uname', models.CharField(max_length=100)),
                ('uemail', models.EmailField(max_length=254)),
                ('query', models.TextField()),
            ],
        ),
    ]
