# Generated by Django 4.1.3 on 2023-04-27 14:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DecodeApp', '0006_blog_catogery_alter_blog_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='view',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='blog',
            name='postedDate',
            field=models.DateField(default=datetime.date(2023, 4, 27)),
        ),
    ]
